In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('data1.csv', index_col = 'show_id')

In [4]:
df.head()

,type,title,director,cast,country,date_added,release_year,rating,duration,genres,language,description,popularity,vote_count,vote_average
show_id,,,,,,,,,,,,,,,
33238,TV Show,Running Man,안재철,"Yoo Jae-suk, Jee Seok-jin, Kim Jong-kook, Haha...",South Korea,2010-07-11,2010,8.241,1 Seasons,"Comedy, Reality",ko,A reality and competition show where members a...,1929.898,187,8.241
32415,TV Show,Conan,NaN,"Conan O'Brien, Andy Richter",United States of America,2010-11-08,2010,7.035,1 Seasons,"Talk, Comedy, News",en,A late night television talk show hosted by C...,1670.580,229,7.035
37757,TV Show,MasterChef Greece,NaN,NaN,Greece,2010-10-03,2010,5.600,1 Seasons,Reality,el,MasterChef Greece is a Greek competitive cooki...,1317.092,6,5.600
75685,TV Show,Prostřeno!,NaN,"Václav Vydra, Jana Boušková",Czech Republic,2010-03-01,2010,6.500,1 Seasons,Reality,cs,The knives (and forks) are out as a group of s...,1095.776,6,6.500
33847,TV Show,The Talk,NaN,"Amanda Kloots, Jerry O'Connell, Akbar Gbaja-Bi...","United States of America, Ireland",2010-10-18,2010,3.400,1 Seasons,Talk,en,A panel of well-known news and entertainment p...,712.070,12,3.400

In [5]:
df.columns

Index(['type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'genres', 'language',
       'description', 'popularity', 'vote_count', 'vote_average'],
      dtype='str')

In [16]:
high_rating = (df['rating'] > 8)

In [24]:
df.loc[high_rating, ['director', 'country', 'genres']].value_counts('country').head(15)

country
Japan                       410
China                       367
United States of America    335
South Korea                 269
Thailand                     62
Russia                       60
Turkey                       58
United Kingdom               56
India                        50
France                       42
Brazil                       42
Pakistan                     42
Germany                      39
Canada                       36
Philippines                  33
Name: count, dtype: int64

In [25]:
df.loc[high_rating, ['director', 'country', 'genres']].value_counts('director').head(15)

director
Yu Je-won              5
Haissam Hussain        4
Oh Choong-hwan         4
Song Hyun-wook         4
Lee Jung-sub           3
Dominic Zapata         3
Jung Dae-yoon          3
Siwaj Sawatmaneekul    3
An Jian                3
An Gil-ho              3
Akira Nishimori        2
Jiang Liu              2
Hong Chang-wook        2
Mehreen Jabbar         2
Kim Sok-yun            2
Name: count, dtype: int64

In [26]:
df.loc[high_rating, ['director', 'country', 'genres']].value_counts('genres').head(15)

genres
Drama                                              400
Reality                                            168
Comedy                                             139
Comedy, Drama                                       94
Documentary                                         90
Drama, Comedy                                       74
Animation, Comedy                                   67
Animation, Action & Adventure, Sci-Fi & Fantasy     44
Talk                                                43
Drama, Family                                       36
Drama, Crime                                        35
Crime, Drama                                        34
Animation, Comedy, Drama                            28
Drama, Mystery                                      24
Animation, Sci-Fi & Fantasy, Action & Adventure     23
Name: count, dtype: int64

In [27]:
df.loc[high_rating, ['director', 'country', 'genres', 'rating']]

,director,country,genres,rating
show_id,,,,
33238,안재철,South Korea,"Comedy, Reality",8.241
1402,NaN,United States of America,"Action & Adventure, Drama, Sci-Fi & Fantasy",8.103
31132,NaN,United States of America,"Animation, Comedy",8.621
33581,NaN,"India, United States of America","Mystery, Drama, Soap",10.000
46296,NaN,United States of America,Drama,8.014
...,...,...,...,...
281061,NaN,United States of America,Documentary,10.000
284533,NaN,Denmark,Documentary,10.000
285281,NaN,Denmark,"Documentary, Reality",10.000
285202,NaN,NaN,"Comedy, Family",10.000
284972,Giulio Manfredonia,NaN,Drama,10.000

In [28]:
countries = ['United States of America', 'India', 'Canada', 'China', 'Japan']

In [29]:
new_filt = df['country'].isin(countries)

In [33]:
df.loc[new_filt, 'country']

show_id
32415     United States of America
1402      United States of America
33384     United States of America
31132     United States of America
64488                       Canada
                    ...
262700                       Japan
281309                       India
279206                       China
273517                       China
277665                       Japan
Name: country, Length: 6620, dtype: str

In [38]:
filt_new = df['genres'].str.contains('Comedy', na=False)

In [39]:
df.loc[filt_new, 'genres']

show_id
33238        Comedy, Reality
32415     Talk, Comedy, News
31132      Animation, Comedy
51038           Comedy, Talk
32651                 Comedy
                 ...
280890         Drama, Comedy
285202        Comedy, Family
284082                Comedy
284892         Comedy, Drama
251815        Comedy, Family
Name: genres, Length: 4576, dtype: str