In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('data1.csv', index_col = 'show_id')

In [3]:
df

,type,title,director,cast,country,date_added,release_year,rating,duration,genres,language,description,popularity,vote_count,vote_average
show_id,,,,,,,,,,,,,,,
33238,TV Show,Running Man,안재철,"Yoo Jae-suk, Jee Seok-jin, Kim Jong-kook, Haha...",South Korea,2010-07-11,2010,8.241,1 Seasons,"Comedy, Reality",ko,A reality and competition show where members a...,1929.898,187,8.241
32415,TV Show,Conan,NaN,"Conan O'Brien, Andy Richter",United States of America,2010-11-08,2010,7.035,1 Seasons,"Talk, Comedy, News",en,A late night television talk show hosted by C...,1670.580,229,7.035
37757,TV Show,MasterChef Greece,NaN,NaN,Greece,2010-10-03,2010,5.600,1 Seasons,Reality,el,MasterChef Greece is a Greek competitive cooki...,1317.092,6,5.600
75685,TV Show,Prostřeno!,NaN,"Václav Vydra, Jana Boušková",Czech Republic,2010-03-01,2010,6.500,1 Seasons,Reality,cs,The knives (and forks) are out as a group of s...,1095.776,6,6.500
33847,TV Show,The Talk,NaN,"Amanda Kloots, Jerry O'Connell, Akbar Gbaja-Bi...","United States of America, Ireland",2010-10-18,2010,3.400,1 Seasons,Talk,en,A panel of well-known news and entertainment p...,712.070,12,3.400
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
284892,TV Show,Sammelanam,NaN,NaN,NaN,2025-02-20,2025,0.000,1 Seasons,"Comedy, Drama",te,Sammelanam is a gripping Telugu web series tha...,3.236,0,0.000
277665,TV Show,Anne Shirley,NaN,"Honoka Inoue, Yasunori Matsumoto, Aya Nakamura...",Japan,2025-04-05,2025,0.000,1 Seasons,"Animation, Drama, Family",ja,It's depict Anne's growth from a girl to a wom...,3.558,0,0.000
284972,TV Show,Le onde del passato,Giulio Manfredonia,"Anna Valle, Giorgio Marchesi, Irene Ferri, Fau...",NaN,2025-02-19,2025,10.000,1 Seasons,Drama,it,NaN,2.913,1,10.000
284613,TV Show,AI히치하이커,NaN,NaN,NaN,2025-02-16,2025,0.000,1 Seasons,NaN,ko,NaN,2.787,0,0.000
251815,TV Show,Alex & Laura's Saturday Night Takeaway,NaN,"Alex Bickerton, Lauren Blake",NaN,2025-02-15,2025,0.000,1 Seasons,"Comedy, Family",en,A gameshow hosted by Alex & Laura filled with ...,2.485,0,0.000

In [4]:
df.loc[75685]

type                                                      TV Show
title                                                  Prostřeno!
director                                                      NaN
cast                                  Václav Vydra, Jana Boušková
country                                            Czech Republic
date_added                                             2010-03-01
release_year                                                 2010
rating                                                        6.5
duration                                                1 Seasons
genres                                                    Reality
language                                                       cs
description     The knives (and forks) are out as a group of s...
popularity                                               1095.776
vote_count                                                      6
vote_average                                                  6.5
Name: 75685, dtype: object

In [6]:
df.sort_index(inplace=True)

In [7]:
df

,type,title,director,cast,country,date_added,release_year,rating,duration,genres,language,description,popularity,vote_count,vote_average
show_id,,,,,,,,,,,,,,,
767,TV Show,Ready Steady Cook,Julian Smith,Rylan Clark,United Kingdom,2020-03-02,2020,6.000,1 Seasons,NaN,en,Rylan Clark-Neal puts the next generation of c...,16.778,1,6.000
877,TV Show,Caprica,NaN,"Eric Stoltz, Esai Morales, Paula Malcomson, Al...",United States of America,2010-01-22,2010,6.900,1 Seasons,"Drama, Sci-Fi & Fantasy",en,"Set 58 years before Battlestar Galactica, Capr...",35.596,364,6.900
1399,TV Show,Game of Thrones,NaN,"Peter Dinklage, Kit Harington, Nikolaj Coster-...","United Kingdom, United States of America",2011-04-17,2011,8.500,1 Seasons,"Sci-Fi & Fantasy, Drama, Action & Adventure",en,Seven noble families fight for control of the ...,812.157,24664,8.500
1401,TV Show,Hell on Wheels,NaN,"Anson Mount, Colm Meaney, Robin McLeavy, Chris...","Canada, United Kingdom, United States of America",2011-11-06,2011,7.600,1 Seasons,"Action & Adventure, Drama, Western",en,"The epic story of post-Civil War America, focu...",119.632,422,7.600
1402,TV Show,The Walking Dead,NaN,"Lauren Cohan, Norman Reedus, Jeffrey Dean Morg...",United States of America,2010-10-31,2010,8.103,1 Seasons,"Action & Adventure, Drama, Sci-Fi & Fantasy",en,Sheriff's deputy Rick Grimes awakens from a co...,485.660,16790,8.103
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
285310,TV Show,Number One on the Call Sheet,NaN,NaN,United States of America,2025-03-27,2025,0.000,1 Seasons,Documentary,en,Two documentaries celebrate the achievements o...,5.379,0,0.000
285311,TV Show,مومولو والأصدقاء,NaN,NaN,NaN,2025-02-01,2025,0.000,1 Seasons,NaN,en,"Momolu, a gentle panda, and his friends have a...",5.379,0,0.000
285314,TV Show,SC+,NaN,NaN,United States of America,2025-03-03,2025,1.000,1 Seasons,News,en,A new daily SportsCenter show highlighting eac...,5.379,1,1.000
285315,TV Show,深深爸讲乐理,NaN,NaN,NaN,2025-02-28,2025,0.000,1 Seasons,NaN,zh,NaN,5.379,0,0.000
285345,TV Show,Love Suddenly,NaN,"Alex Lam Tak-Shun, Bella Lam Wing Tung",Hong Kong,2025-03-03,2025,0.000,1 Seasons,NaN,cn,NaN,3.842,0,0.000