In [224]:
import pandas as pd
import numpy as np

In [225]:
df = pd.read_csv('netflix_titles.csv')

INSPECTION

In [226]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   str
 1   type          8807 non-null   str
 2   title         8807 non-null   str
 3   director      6173 non-null   str
 4   cast          7982 non-null   str
 5   country       7976 non-null   str
 6   date_added    8797 non-null   str
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   str
 9   duration      8804 non-null   str
 10  listed_in     8807 non-null   str
 11  description   8807 non-null   str
dtypes: int64(1), str(11)
memory usage: 825.8 KB

In [227]:
df.describe()

       release_year
count   8807.000000
mean    2014.180198
std        8.819312
min     1925.000000
25%     2013.000000
50%     2017.000000
75%     2019.000000
max     2021.000000

In [228]:
df.shape

(8807, 12)

In [229]:
df.columns

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'description'],
      dtype='str')

In [230]:
df.isnull().sum()

show_id            0
type               0
title              0
director        2634
cast             825
country          831
date_added        10
release_year       0
rating             4
duration           3
listed_in          0
description        0
dtype: int64

CLEANING

In [231]:
filt = df['duration'].isnull()

In [232]:
df['rating'].unique()

<StringArray>
[   'PG-13',    'TV-MA',       'PG',    'TV-14',    'TV-PG',     'TV-Y',
    'TV-Y7',        'R',     'TV-G',        'G',    'NC-17',   '74 min',
   '84 min',   '66 min',       'NR',        nan, 'TV-Y7-FV',       'UR']
Length: 18, dtype: str

In [233]:
filt = df['rating'].str.contains('min')

In [234]:
df.loc[filt, 'duration'] = df.loc[filt, 'rating']

In [235]:
df.loc[filt]['duration']

5541    74 min
5794    84 min
5813    66 min
Name: duration, dtype: str

In [236]:
df.loc[filt, 'rating'] = np.nan

In [237]:
df.loc[filt, 'rating']

5541    NaN
5794    NaN
5813    NaN
Name: rating, dtype: str

In [238]:
filt = df['rating'].isnull()
df.loc[filt]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
5541,s5542,Movie,Louis C.K. 2017,Louis C.K.,Louis C.K.,United States,"April 4, 2017",2017,NaN,74 min,Movies,"Louis C.K. muses on religion, eternal love, gi..."
5794,s5795,Movie,Louis C.K.: Hilarious,Louis C.K.,Louis C.K.,United States,"September 16, 2016",2010,NaN,84 min,Movies,Emmy-winning comedy writer Louis C.K. brings h...
5813,s5814,Movie,Louis C.K.: Live at the Comedy Store,Louis C.K.,Louis C.K.,United States,"August 15, 2016",2015,NaN,66 min,Movies,The comic puts his trademark hilarious/thought...
5989,s5990,Movie,13TH: A Conversation with Oprah Winfrey & Ava ...,NaN,"Oprah Winfrey, Ava DuVernay",NaN,"January 26, 2017",2017,NaN,37 min,Movies,Oprah Winfrey sits down with director Ava DuVe...
6827,s6828,TV Show,Gargantia on the Verdurous Planet,NaN,"Kaito Ishikawa, Hisako Kanemoto, Ai Kayano, Ka...",Japan,"December 1, 2016",2013,NaN,1 Season,"Anime Series, International TV Shows","After falling through a wormhole, a space-dwel..."
7312,s7313,TV Show,Little Lunch,NaN,"Flynn Curry, Olivia Deeble, Madison Lu, Oisín ...",Australia,"February 1, 2018",2015,NaN,1 Season,"Kids' TV, TV Comedies","Adopting a child's perspective, this show take..."
7537,s7538,Movie,My Honor Was Loyalty,Alessandro Pepe,"Leone Frisa, Paolo Vaccarino, Francesco Miglio...",Italy,"March 1, 2017",2015,NaN,115 min,Dramas,"Amid the chaos and horror of World War II, a c..."

In [239]:
df.dropna(subset='rating', inplace=True)

In [240]:
df.isnull().sum()

show_id            0
type               0
title              0
director        2631
cast             825
country          830
date_added        10
release_year       0
rating             0
duration           0
listed_in          0
description        0
dtype: int64

In [241]:
filt = df['date_added'].isnull()
df.loc[filt]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
6066,s6067,TV Show,A Young Doctor's Notebook and Other Stories,NaN,"Daniel Radcliffe, Jon Hamm, Adam Godley, Chris...",United Kingdom,NaN,2013,TV-MA,2 Seasons,"British TV Shows, TV Comedies, TV Dramas","Set during the Russian Revolution, this comic ..."
6174,s6175,TV Show,Anthony Bourdain: Parts Unknown,NaN,Anthony Bourdain,United States,NaN,2018,TV-PG,5 Seasons,Docuseries,This CNN original series has chef Anthony Bour...
6795,s6796,TV Show,Frasier,NaN,"Kelsey Grammer, Jane Leeves, David Hyde Pierce...",United States,NaN,2003,TV-PG,11 Seasons,"Classic & Cult TV, TV Comedies",Frasier Crane is a snooty but lovable Seattle ...
6806,s6807,TV Show,Friends,NaN,"Jennifer Aniston, Courteney Cox, Lisa Kudrow, ...",United States,NaN,2003,TV-14,10 Seasons,"Classic & Cult TV, TV Comedies",This hit sitcom follows the merry misadventure...
6901,s6902,TV Show,Gunslinger Girl,NaN,"Yuuka Nanri, Kanako Mitsuhashi, Eri Sendai, Am...",Japan,NaN,2008,TV-14,2 Seasons,"Anime Series, Crime TV Shows","On the surface, the Social Welfare Agency appe..."
7196,s7197,TV Show,Kikoriki,NaN,Igor Dmitriev,NaN,NaN,2010,TV-Y,2 Seasons,Kids' TV,A wacky rabbit and his gang of animal pals hav...
7254,s7255,TV Show,La Familia P. Luche,NaN,"Eugenio Derbez, Consuelo Duval, Luis Manuel Áv...",United States,NaN,2012,TV-14,3 Seasons,"International TV Shows, Spanish-Language TV Sh...","This irreverent sitcom featues Ludovico, Feder..."
7406,s7407,TV Show,Maron,NaN,"Marc Maron, Judd Hirsch, Josh Brener, Nora Zeh...",United States,NaN,2016,TV-MA,4 Seasons,TV Comedies,"Marc Maron stars as Marc Maron, who interviews..."
7847,s7848,TV Show,Red vs. Blue,NaN,"Burnie Burns, Jason Saldaña, Gustavo Sorola, G...",United States,NaN,2015,NR,13 Seasons,"TV Action & Adventure, TV Comedies, TV Sci-Fi ...","This parody of first-person shooter games, mil..."
8182,s8183,TV Show,The Adventures of Figaro Pho,NaN,"Luke Jurevicius, Craig Behenna, Charlotte Haml...",Australia,NaN,2015,TV-Y7,2 Seasons,"Kids' TV, TV Comedies","Imagine your worst fears, then multiply them: ..."

In [242]:
df.isnull().sum()

show_id            0
type               0
title              0
director        2631
cast             825
country          830
date_added        10
release_year       0
rating             0
duration           0
listed_in          0
description        0
dtype: int64

In [243]:
# missing values in date_added, directors, case, do not matter much so we need not deal with them.
# our analysis will not be hampered due to these missing values

In [244]:
df['country'] = df['country'].fillna('unknown')

In [245]:
df.isnull().sum()

show_id            0
type               0
title              0
director        2631
cast             825
country            0
date_added        10
release_year       0
rating             0
duration           0
listed_in          0
description        0
dtype: int64

In [246]:
df['title'].unique()

<StringArray>
[            'Dick Johnson Is Dead',                    'Blood & Water',
                        'Ganglands',            'Jailbirds New Orleans',
                     'Kota Factory',                    'Midnight Mass',
 'My Little Pony: A New Generation',                          'Sankofa',
    'The Great British Baking Show',                     'The Starling',
 ...
                        'Zak Storm',                         'Zed Plus',
                            'Zenda',               'Zindagi Gulzar Hai',
                          'Zinzana',                           'Zodiac',
                      'Zombie Dumb',                       'Zombieland',
                             'Zoom',                           'Zubaan']
Length: 8800, dtype: str

In [247]:
df.shape

(8800, 12)

In [248]:
# no duplicates as there are 8800 unique titles which is equal to the total titles

In [249]:
df['rating'].unique()

<StringArray>
[   'PG-13',    'TV-MA',       'PG',    'TV-14',    'TV-PG',     'TV-Y',
    'TV-Y7',        'R',     'TV-G',        'G',    'NC-17',       'NR',
 'TV-Y7-FV',       'UR']
Length: 14, dtype: str

In [250]:
df['listed_in'].unique()

<StringArray>
[                                                'Documentaries',
               'International TV Shows, TV Dramas, TV Mysteries',
 'Crime TV Shows, International TV Shows, TV Action & Adventure',
                                        'Docuseries, Reality TV',
        'International TV Shows, Romantic TV Shows, TV Comedies',
                            'TV Dramas, TV Horror, TV Mysteries',
                                      'Children & Family Movies',
              'Dramas, Independent Movies, International Movies',
                                  'British TV Shows, Reality TV',
                                              'Comedies, Dramas',
 ...
                               'Comedies, Dramas, Sports Movies',
         'Action & Adventure, Romantic Movies, Sci-Fi & Fantasy',
                        'Classic & Cult TV, TV Sci-Fi & Fantasy',
                           'Comedies, Cult Movies, LGBTQ Movies',
                     'Comedies, Horror Movies, Sci-Fi & Fantasy',
                   'Action & Adventure, Comedies, Horror Movies',
                  'Classic & Cult TV, Crime TV Shows, TV Dramas',
              'Action & Adventure, Documentaries, Sports Movies',
           'International Movies, LGBTQ Movies, Romantic Movies',
                                'Cult Movies, Dramas, Thrillers']
Length: 514, dtype: str

In [251]:
df['points'] = np.random.uniform(1.0, 10.0, size=[8800,1])

ANALYSIS

In [252]:
def top_movies():
    global df
    filt = df['type'] == 'Movie'
    top_movies = df.loc[filt].nlargest(10, 'points')
    
    movie_titles = top_movies['title']
    movie_points = top_movies['points']

    best_movies_df = pd.concat([movie_titles, movie_points], axis=1)
    print ("The best movies according to points are as follows:\n")
    return best_movies_df

In [253]:
def common_genres():
    global df

    genres_common = df['listed_in'].value_counts().head(5)
    print ("The most common genres are as follows:\n")

    return genres_common

In [254]:
def common_countries():
    global df
    print("A large chunk of shows and movies are from the following countries: ")
    return df['country'].value_counts().head(5)

In [255]:
def average_per_genre():
    global df
    genre = input("Enter genre: ")
    filt = df['listed_in'].str.contains(genre, case=False)

    print("The average points for the chosen genre are: ")
    return df.loc[filt, 'points'].mean()

In [256]:
def common_directors():
    global df
    print ("The most common genres are as follows:\n")
    return df['director'].value_counts().head(5)

In [257]:
df['duration'].unique()

<StringArray>
[   '90 min', '2 Seasons',  '1 Season',    '91 min',   '125 min', '9 Seasons',
   '104 min',   '127 min', '4 Seasons',    '67 min',
 ...
    '43 min',   '200 min',   '196 min',   '167 min',   '178 min',   '228 min',
    '18 min',   '205 min',   '201 min',   '191 min']
Length: 220, dtype: str

In [258]:
df['duration'] = df['duration'].str.replace('min', '', regex=False).str.strip()
df['duration'] = df['duration'].str.replace('Seasons', '', regex=False).str.strip()
df['duration'] = df['duration'].str.replace('Season', '', regex=False).str.strip()

In [259]:
df['duration'].unique()

<StringArray>
[ '90',   '2',   '1',  '91', '125',   '9', '104', '127',   '4',  '67',
 ...
  '43', '200', '196', '167', '178', '228',  '18', '205', '201', '191']
Length: 210, dtype: str

In [260]:
df['duration'] = df['duration'].astype(float)

FACTORED ANALYSIS

In [261]:
def mean_runtime_by_country():
    global df

    country = input('Which country? ')
    
    country_grp = df.loc[df['type'] == 'Movie'].groupby('country')

    print("The average runtime in minutes for the chosen country is:")
    return country_grp['duration'].agg(['mean']).loc[country]

In [262]:
def mean_points_by_country():
    global df

    country = input('Which country? ')
    
    country_grp = df.loc[df['type'] == 'Movie'].groupby('country')

    print("The average points in minutes for the chosen country is:")
    return country_grp['points'].agg(['mean']).loc[country]

In [263]:
def year_wise_points():
    global df
    year_grp = df.groupby('release_year')
    year_mean = year_grp['points'].mean()
    year_mean.sort_values(ascending=False, inplace=True)
    return year_mean

In [264]:
def runtime_by_genres_movie():
    global df
    genre_grp = df.loc[df['type'] == 'Movie'].groupby('listed_in')
    genre_points = genre_grp['duration'].mean()
    genre_points.sort_values(ascending=False, inplace=True)
    print("In our data, we can notice that classic movies have the highest runtime,\nmaybe due to their timelessness and cultural impact")
    return genre_points

In [265]:
def runtime_by_genres_show():
    global df
    genre_grp = df.loc[df['type'] == 'TV Show'].groupby('listed_in')
    genre_points = genre_grp['duration'].mean()
    genre_points.sort_values(ascending=False, inplace=True)
    print("In our data we can notice that classic and cult TV have the highest runtime,\npossibly due to their higher populatiry and neverending scripts")
    return genre_points

RUNTIME AND RATING RELATION ANALYSIS

In [266]:
def runtime_rating_relation_movie():
    global df
    runtime = df.loc[df['type'] == 'Movie', 'duration']
    rating = df.loc[df['type'] == 'Movie', 'points']

    new_df = pd.concat([runtime, rating], axis=1)
    correlation = np.corrcoef(new_df['duration'] , new_df['points'])

    if abs(correlation[0,1]) > 0.70:
        return("The two are somewhat correlated")

    else: 
        return("The two are not related")

In [267]:
df['duration_hours'] = df['duration'] / 60

In [268]:
df.loc[df['type'] == 'TV Show' , 'duration_hours'] = np.nan

In [269]:
filt1 = ( (df['type'] == 'Movie') & (df['duration_hours'] > 2.5))
df.loc[filt1, 'category'] = 'long'

filt2 = ( (df['type'] == 'Movie') & (df['duration_hours'] <= 2.5) & (df['duration_hours'] >= 1.5) )
df.loc[filt2, 'category'] = 'medium'

filt3 = ( (df['type'] == 'Movie') & (df['duration_hours'] < 1.5))
df.loc[filt3, 'category'] = 'short'

filt4 = ( (df['type'] == 'TV Show') & (df['duration'] > 6))
df.loc[filt4, 'category'] = 'long'

filt5 = ( (df['type'] == 'TV Show') & (df['duration'] <= 6) & (df['duration'] >= 3) )
df.loc[filt5, 'category'] = 'medium'

filt6 = ( (df['type'] == 'TV Show') & (df['duration'] < 3))
df.loc[filt6, 'category'] = 'short'

In [270]:
df.columns

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'description',
       'points', 'duration_hours', 'category'],
      dtype='str')

MULTI-FACTOR RANKING SYSTEM

In [271]:
def ranking_system():
    global df
    # points get 70% weightage in this ranking system.
    # release_year gets 10% weightage
    # category gets 10% weightage
    # country gets 10% weightage

    # these are kind of a bit senseless since i did not have much relevant columns to work with

    coin_points = df['points'] / 10 * 70
    
    df['coin_release_year'] = df['release_year']
    filt1 = (df['release_year'] > 2015)
    filt2 = (df['release_year'] > 2005) & (df['release_year'] <= 2015)
    filt3 = (df['release_year'] > 1995) & (df['release_year'] <= 2005)
    filt4 = (df['release_year'] > 1980) & (df['release_year'] <= 1995)
    filt5 = (df['release_year'] > 1970) & (df['release_year'] <= 1980)
    filt6 = (df['release_year'] <= 1970)

    df.loc[filt1, 'coin_release_year'] = 10
    df.loc[filt2, 'coin_release_year'] = 8
    df.loc[filt3, 'coin_release_year'] = 6
    df.loc[filt4, 'coin_release_year'] = 4
    df.loc[filt5, 'coin_release_year'] = 2
    df.loc[filt6, 'coin_release_year'] = 0


    coin_release_year = df['coin_release_year']
    df = df.drop('coin_release_year', axis=1)

    df['coin_category'] = df['category']
    df['coin_category'] = df['coin_category'].str.replace('medium', '10')
    df['coin_category'] = df['coin_category'].str.replace('long', '5')
    df['coin_category'] = df['coin_category'].str.replace('short', '5')
    
    df['coin_category'] = df['coin_category'].astype(float)

    coin_category = df['coin_category']
    df = df.drop('coin_category', axis=1) 

    df['coin_country'] = 0

    df.loc[df['country'] == 'India', 'coin_country'] = 10
    df.loc[df['country'] == 'United States of America', 'coin_country'] = 8
    df.loc[df['country'] == 'United Kingdom', 'coin_country'] = 6
    df.loc[df['country'] == 'Japan', 'coin_country'] = 4
    df.loc[df['country'] == 'South Korea', 'coin_country'] = 2

    coin_country = df['coin_country']
    df = df.drop('coin_country', axis=1)

    coins = coin_points + coin_category + coin_country

    df['coins'] = coins
    
    df.sort_values(by= 'coins', ascending=False, inplace=True)
    return df

In [272]:
df.isnull().sum()

show_id              0
type                 0
title                0
director          2631
cast               825
country              0
date_added          10
release_year         0
rating               0
duration             0
listed_in            0
description          0
points               0
duration_hours    2674
category             0
dtype: int64

In [273]:
top_movies()

The best movies according to points are as follows:

                                 title    points
5102       Goon: Last of the Enforcers  9.997810
1805                   Bending the Arc  9.996844
8486                          The Ring  9.996715
1185                    Who's the Boss  9.996442
4800                 Tum Milo Toh Sahi  9.995657
498                              Clash  9.994478
2150  Berlin, Berlin: Lolle on the Run  9.993391
7360           Lucky: No Time for Love  9.992135
6204                    Babam ve Oğlum  9.987203
1475            Too Handsome to Handle  9.982934

In [274]:
common_genres()

The most common genres are as follows:

listed_in
Dramas, International Movies                        362
Documentaries                                       359
Stand-Up Comedy                                     334
Comedies, Dramas, International Movies              274
Dramas, Independent Movies, International Movies    252
Name: count, dtype: int64

In [275]:
common_countries()

A large chunk of shows and movies are from the following countries:

country
United States     2815
India              972
unknown            830
United Kingdom     419
Japan              244
Name: count, dtype: int64

In [276]:
average_per_genre()

The average points for the chosen genre are:

np.float64(5.525282734216281)

In [277]:
common_directors()

The most common genres are as follows:

director
Rajiv Chilaka             19
Raúl Campos, Jan Suter    18
Suhas Kadav               16
Marcus Raboy              16
Jay Karas                 14
Name: count, dtype: int64

In [278]:
mean_runtime_by_country()

The average runtime in minutes for the chosen country is:

mean    126.922732
Name: India, dtype: float64

In [287]:
mean_points_by_country()

The average points in minutes for the chosen country is:

mean    5.506763
Name: India, dtype: float64

In [279]:
year_wise_points()

release_year
1965    7.946556
1956    7.813854
1962    7.548645
1946    7.103624
1943    6.956952
          ...
1966    3.427468
1964    3.288480
1942    3.287196
1961    2.425446
1947    2.039222
Name: points, Length: 74, dtype: float64

In [280]:
runtime_by_genres_movie()

In our data, we can notice that classic movies have the highest runtime,
maybe due to their timelessness and cultural impact

listed_in
Classic Movies, Music & Musicals                            173.000000
Action & Adventure, Cult Movies, Dramas                     172.000000
Action & Adventure, Classic Movies, International Movies    166.000000
Cult Movies, Dramas, Thrillers                              158.000000
Classic Movies, Dramas, Romantic Movies                     153.666667
                                                               ...
Children & Family Movies, Comedies, LGBTQ Movies             46.000000
Movies                                                       45.641509
Action & Adventure, Documentaries, Sports Movies             40.000000
Anime Features, Documentaries                                36.000000
Comedies, Music & Musicals, Sports Movies                    30.000000
Name: duration, Length: 278, dtype: float64

In [281]:
runtime_by_genres_show()

In our data we can notice that classic and cult TV have the highest runtime,
possibly due to their higher populatiry and neverending scripts

listed_in
Classic & Cult TV, TV Action & Adventure, TV Horror              9.0
Classic & Cult TV, TV Comedies                                   9.0
TV Action & Adventure, TV Comedies, TV Sci-Fi & Fantasy          8.0
Crime TV Shows, TV Action & Adventure, TV Sci-Fi & Fantasy       7.0
Classic & Cult TV, TV Action & Adventure, TV Sci-Fi & Fantasy    7.0
                                                                ...
TV Action & Adventure, TV Dramas, TV Mysteries                   1.0
TV Comedies, TV Mysteries                                        1.0
TV Dramas, TV Sci-Fi & Fantasy, TV Thrillers                     1.0
TV Horror, TV Mysteries, Teen TV Shows                           1.0
TV Shows                                                         1.0
Name: duration, Length: 236, dtype: float64

In [282]:
runtime_rating_relation_movie()

'The two are not related'

In [283]:
ranking_system()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,points,duration_hours,category,coins
4800,s4801,Movie,Tum Milo Toh Sahi,Kabir Sadanand,"Nana Patekar, Dimple Kapadia, Sunil Shetty, Vi...",India,"July 1, 2018",2010,TV-14,128.0,"Comedies, Dramas, International Movies",An astute but old-fashioned law clerk steps up...,9.995657,2.133333,medium,89.969597
7360,s7361,Movie,Lucky: No Time for Love,"Radhika Rao, Vinay Sapru","Salman Khan, Sneha Ullal, Mithun Chakraborty, ...",India,"November 15, 2017",2005,TV-14,131.0,"Dramas, International Movies, Romantic Movies","During an uprising in Russia's St. Petersburg,...",9.992135,2.183333,medium,89.944948
4182,s4183,Movie,Soni,Ivan Ayr,"Geetika Vidya Ohlyan, Saloni Batra, Mohinder G...",India,"January 18, 2019",2018,TV-MA,97.0,"Dramas, Independent Movies, International Movies","While fighting crimes against women in Delhi, ...",9.976184,1.616667,medium,89.833289
4465,s4466,Movie,Yeh Hai Bakrapur,NaN,"Amit Sial, Yoshika Verma, Anshuman Jha, Asif B...",India,"November 1, 2018",2014,TV-PG,95.0,"Comedies, Dramas, Independent Movies",A poor family’s goat suddenly acquires divine ...,9.914228,1.583333,medium,89.399593
5778,s5779,Movie,Umrika,Prashant Nair,"Suraj Sharma, Tony Revolori, Smita Tambe, Adil...",India,"October 1, 2016",2015,TV-MA,96.0,"Dramas, Independent Movies, International Movies",An ambitious man leaves his small Indian villa...,9.913688,1.600000,medium,89.395819
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
430,s431,TV Show,Sexy Beasts,NaN,NaN,unknown,"July 21, 2021",2021,TV-14,1.0,"British TV Shows, International TV Shows, Real...","Hoping to say goodbye to superficial dating, r...",1.008295,NaN,short,12.058062
3295,s3296,TV Show,Green Eggs and Ham,NaN,"Michael Douglas, Adam Devine, Keegan-Michael K...","United Kingdom, Canada, United States","November 8, 2019",2019,TV-Y7,1.0,"Kids' TV, TV Action & Adventure, TV Comedies","On a road trip to save an endangered animal, p...",1.008227,NaN,short,12.057592
3317,s3318,Movie,Big Time Movie,Savage Steve Holland,"Kendall Schmidt, James Maslow, Carlos PenaVega...","United States, Canada","November 2, 2019",2012,TV-PG,68.0,"Children & Family Movies, Comedies, Music & Mu...",Big Time Rush heads to London for their first ...,1.008180,1.133333,short,12.057258
7029,s7030,TV Show,Huntik: Secrets and Seekers,NaN,"Yuri Lowenthal, Drew Aaron, Karen Strassman, M...","United States, Italy","January 1, 2018",2011,TV-Y7,2.0,Kids' TV,A high school student searching for his missin...,1.006223,NaN,short,12.043563
7343,s7344,TV Show,Love Cuisine,NaN,"Lego Lee, Allison Lin, Duncan Chow, Nita Lei, ...",Taiwan,"August 1, 2016",2015,TV-MA,1.0,"International TV Shows, Romantic TV Shows, TV ...",A successful Taiwanese chef moves home from Eu...,1.006121,NaN,short,12.042847

In [284]:
new_df = df.head(10)

In [285]:
df.to_csv('netflix_cleaned.csv', index=False)

In [286]:
new_df.to_csv('top_movies_shows.csv', index=False)