In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('data1.csv')

In [4]:
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,genres,language,description,popularity,vote_count,vote_average
0,33238,TV Show,Running Man,안재철,"Yoo Jae-suk, Jee Seok-jin, Kim Jong-kook, Haha...",South Korea,2010-07-11,2010,8.241,1 Seasons,"Comedy, Reality",ko,A reality and competition show where members a...,1929.898,187,8.241
1,32415,TV Show,Conan,NaN,"Conan O'Brien, Andy Richter",United States of America,2010-11-08,2010,7.035,1 Seasons,"Talk, Comedy, News",en,A late night television talk show hosted by C...,1670.580,229,7.035
2,37757,TV Show,MasterChef Greece,NaN,NaN,Greece,2010-10-03,2010,5.600,1 Seasons,Reality,el,MasterChef Greece is a Greek competitive cooki...,1317.092,6,5.600
3,75685,TV Show,Prostřeno!,NaN,"Václav Vydra, Jana Boušková",Czech Republic,2010-03-01,2010,6.500,1 Seasons,Reality,cs,The knives (and forks) are out as a group of s...,1095.776,6,6.500
4,33847,TV Show,The Talk,NaN,"Amanda Kloots, Jerry O'Connell, Akbar Gbaja-Bi...","United States of America, Ireland",2010-10-18,2010,3.400,1 Seasons,Talk,en,A panel of well-known news and entertainment p...,712.070,12,3.400

In [8]:
df['popularity'].sort_values(ascending=False)

5000     6421.923
4000     4925.253
2000     3414.466
8000     2987.485
14000    2885.720
           ...
15992       2.487
15999       2.485
15993       2.418
15978       2.413
15981       2.323
Name: popularity, Length: 16000, dtype: float64

In [14]:
df['popularity'].head(5).mean

<bound method Series.mean of 0    1929.898
1    1670.580
2    1317.092
3    1095.776
4     712.070
Name: popularity, dtype: float64>

In [17]:
df.describe()

,show_id,release_year,rating,popularity,vote_count,vote_average
count,16000.000000,16000.000000,16000.000000,16000.000000,16000.000000,16000.000000
mean,126567.673375,2017.500000,5.417107,64.850984,107.014313,5.417107
std,75640.760545,4.609916,3.266492,139.387289,607.461581,3.266492
min,767.000000,2010.000000,0.000000,2.323000,0.000000,0.000000
25%,67867.750000,2013.750000,2.700000,24.874750,1.000000,2.700000
50%,94380.500000,2017.500000,6.800000,36.187500,4.000000,6.800000
75%,206920.750000,2021.250000,7.800000,62.187500,30.000000,7.800000
max,285345.000000,2025.000000,10.000000,6421.923000,24664.000000,10.000000

In [19]:
df['rating'].describe()

count    16000.000000
mean         5.417107
std          3.266492
min          0.000000
25%          2.700000
50%          6.800000
75%          7.800000
max         10.000000
Name: rating, dtype: float64

In [20]:
df['type'].value_counts()

type
TV Show    16000
Name: count, dtype: int64

In [26]:
df['genres'].value_counts(normalize=True)

genres
Drama                                         0.182617
Reality                                       0.073473
Comedy                                        0.071077
Comedy, Drama                                 0.034340
Documentary                                   0.030880
                                                ...
Mystery, Family, Talk                         0.000067
Sci-Fi & Fantasy, Crime                       0.000067
Mystery, Reality, Drama                       0.000067
Documentary, Family, Reality                  0.000067
Action & Adventure, Animation, Drama, Kids    0.000067
Name: proportion, Length: 1218, dtype: float64

In [27]:
# grouping

In [29]:
country_grp = df.groupby('country')

In [31]:
country_grp.get_group('United States of America')

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,genres,language,description,popularity,vote_count,vote_average
1,32415,TV Show,Conan,NaN,"Conan O'Brien, Andy Richter",United States of America,2010-11-08,2010,7.035,1 Seasons,"Talk, Comedy, News",en,A late night television talk show hosted by C...,1670.580,229,7.035
7,1402,TV Show,The Walking Dead,NaN,"Lauren Cohan, Norman Reedus, Jeffrey Dean Morg...",United States of America,2010-10-31,2010,8.103,1 Seasons,"Action & Adventure, Drama, Sci-Fi & Fantasy",en,Sheriff's deputy Rick Grimes awakens from a co...,485.660,16790,8.103
8,33384,TV Show,Zone,NaN,"Michael Underwood, Angellica Bell",United States of America,2010-05-20,2010,0.000,1 Seasons,NaN,en,The Zone is the name given to a shopping and g...,489.739,0,0.000
9,31132,TV Show,Regular Show,NaN,"J.G. Quintel, William Salyers, Mark Hamill, Sa...",United States of America,2010-09-06,2010,8.621,1 Seasons,"Animation, Comedy",en,The surreal misadventures of two best friends ...,426.107,2045,8.621
15,31917,TV Show,Pretty Little Liars,NaN,"Lucy Hale, Troian Bellisario, Ashley Benson, S...",United States of America,2010-06-08,2010,8.000,1 Seasons,"Drama, Mystery",en,Based on the Pretty Little Liars series of you...,389.580,2637,8.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15937,281061,TV Show,The Swift Effect,NaN,Taylor Swift,United States of America,2025-01-04,2025,10.000,1 Seasons,Documentary,en,An exploration of the vast economic impact Tay...,4.424,1,10.000
15938,282237,TV Show,What Drives You with John Cena,NaN,John Cena,United States of America,2025-01-21,2025,0.000,1 Seasons,Talk,en,"John Cena fuels his two biggest passions, cars...",2.585,0,0.000
15947,285120,TV Show,The Anime Business,NaN,Justin Sevakis,United States of America,2025-02-24,2025,0.000,1 Seasons,Documentary,en,Justin Sevakis sits down with industry veteran...,3.610,0,0.000
15962,285314,TV Show,SC+,NaN,NaN,United States of America,2025-03-03,2025,1.000,1 Seasons,News,en,A new daily SportsCenter show highlighting eac...,5.379,1,1.000
15964,285310,TV Show,Number One on the Call Sheet,NaN,NaN,United States of America,2025-03-27,2025,0.000,1 Seasons,Documentary,en,Two documentaries celebrate the achievements o...,5.379,0,0.000

In [36]:
country_grp.get_group('India')['genres'].value_counts()

genres
Drama                               110
Drama, Soap                          25
Drama, Family                        25
Comedy                               17
Reality                              16
                                   ...
Drama, War & Politics                 1
Action & Adventure, Crime             1
Mystery, Kids, Sci-Fi & Fantasy       1
Sci-Fi & Fantasy, Mystery             1
Drama, Crime, Action & Adventure      1
Name: count, Length: 75, dtype: int64

In [38]:
country_grp['genres'].value_counts().head(50)

country                                             genres
Algeria                                             Action & Adventure, Comedy                       1
Angola, Brazil                                      Soap                                             1
Argentina                                           Drama                                            8
                                                    Soap                                             5
                                                    Drama, Comedy                                    3
                                                    Drama, Crime                                     3
                                                    Crime, Drama                                     3
                                                    Drama, Soap                                      3
                                                    Comedy, Family                                   2
                                                    Talk                                             2
                                                    Comedy, Drama                                    2
                                                    Comedy, Soap                                     1
                                                    Soap, Drama, Mystery, Sci-Fi & Fantasy           1
                                                    Drama, Mystery                                   1
                                                    Kids, Family                                     1
                                                    Drama, Family, Soap                              1
                                                    Soap, Drama                                      1
                                                    Drama, Sci-Fi & Fantasy, Mystery                 1
                                                    Family, Reality                                  1
                                                    Action & Adventure, Drama, Sci-Fi & Fantasy      1
                                                    Comedy, Drama, Soap, Family                      1
                                                    Comedy, Family, Drama                            1
                                                    Reality                                          1
                                                    Documentary, Reality                             1
                                                    Comedy                                           1
                                                    Family, Comedy, Soap                             1
                                                    Family                                           1
                                                    Soap, Comedy, Drama                              1
                                                    Drama, Kids, Soap, Comedy                        1
                                                    Drama, Family                                    1
                                                    Drama, Soap, Family                              1
                                                    Soap, Kids, Family, Comedy                       1
Argentina, Brazil                                   Drama, Comedy, Soap, Family                      1
                                                    Kids                                             1
Argentina, Brazil, Chile, United States of America  Reality                                          1
Argentina, Chile                                    Comedy, Drama                                    1
                                                    Reality                                          1
Argentina, Chile, Mexico                            Reality                                          1
Argentina, Chile, United States of America          Drama                                            1
Argentina, Colombia, Mexico, Uruguay                Documentary                                      1
Argentina, France                                   Animation                                        1
Argentina, Mexico                                   Drama, Family, Comedy, Soap                      1
                                                    Comedy, Drama                                    1
Argentina, Mexico, United States of America         Drama                                            1
Argentina, Spain                                    Drama, Comedy                                    1
                                                    Sci-Fi & Fantasy, Comedy, Family, Drama, Soap    1
                                                    Family, Drama, Comedy, Soap                      1
Argentina, Spain, Mexico                            Drama, Mystery                                   1
Argentina, United Kingdom                           Comedy                                           1
Argentina, United States of America                 Drama, Crime                                     1
Name: count, dtype: int64

In [48]:
country_grp['popularity'].median().loc[['United States of America', 'India', 'United Kingdom', 'Japan', 'South Korea', 'China']]

country
United States of America    42.3390
India                       53.9865
United Kingdom              33.3140
Japan                       31.0320
South Korea                 36.8445
China                       32.6520
Name: popularity, dtype: float64

In [49]:
country_grp['popularity'].agg(['median', 'mean'])

                                                      median        mean
country
Algeria                                             196.1590  196.159000
Angola, Brazil                                      245.5910  245.591000
Argentina                                            40.2570   69.422925
Argentina, Brazil                                    46.5495   46.549500
Argentina, Brazil, Chile, United States of America   29.4730   29.473000
...                                                      ...         ...
Venezuela, Mexico                                   102.6300  102.630000
Venezuela, United States of America                  31.5260   31.526000
Venezuela, United States of America, Colombia        25.9100   25.910000
Venezuela, United States of America, Spain           21.8820   21.882000
Vietnam                                              25.4865   26.550900

[564 rows x 2 columns]

In [50]:
df['popularity'].max()

np.float64(6421.923)

In [51]:
country_grp['popularity'].agg(['median', 'mean']).loc['Canada']

median    43.583000
mean      72.207887
Name: Canada, dtype: float64

In [55]:
filt = df['country'] == 'India'
df.loc[filt]['genres'].str.contains('Comedy').sum()

np.int64(66)

In [64]:
# 66 shows from india on netflix are comedy genre

In [70]:
def no_of_true(genre):
    return genre.str.contains('Comedy').sum()

In [82]:
country_grp['genres'].apply(lambda x: x.str.contains('Comedy'))['India'].sum()

np.int64(66)

In [84]:
country_grp['genres'].apply(no_of_true)['India']

np.int64(66)

In [90]:
country_grp['genres'].apply(no_of_true)

country
Algeria                                                1
Angola, Brazil                                         0
Argentina                                             15
Argentina, Brazil                                      1
Argentina, Brazil, Chile, United States of America     0
                                                      ..
Venezuela, Mexico                                      0
Venezuela, United States of America                    0
Venezuela, United States of America, Colombia          0
Venezuela, United States of America, Spain             0
Vietnam                                                4
Name: genres, Length: 564, dtype: int64

In [94]:
country_grp['show_id'].count()

country
Algeria                                                1
Angola, Brazil                                         1
Argentina                                             53
Argentina, Brazil                                      2
Argentina, Brazil, Chile, United States of America     1
                                                      ..
Venezuela, Mexico                                      1
Venezuela, United States of America                    2
Venezuela, United States of America, Colombia          1
Venezuela, United States of America, Spain             1
Vietnam                                               10
Name: show_id, Length: 564, dtype: int64

In [97]:
country_grp['genres'].apply(no_of_true) / country_grp['show_id'].count()

country
Algeria                                               1.000000
Angola, Brazil                                        0.000000
Argentina                                             0.283019
Argentina, Brazil                                     0.500000
Argentina, Brazil, Chile, United States of America    0.000000
                                                        ...
Venezuela, Mexico                                     0.000000
Venezuela, United States of America                   0.000000
Venezuela, United States of America, Colombia         0.000000
Venezuela, United States of America, Spain            0.000000
Vietnam                                               0.400000
Length: 564, dtype: float64

In [101]:
country_grp['genres'].apply(lambda x: x.str.contains('Comedy').sum() / len(x) )

country
Algeria                                               1.000000
Angola, Brazil                                        0.000000
Argentina                                             0.283019
Argentina, Brazil                                     0.500000
Argentina, Brazil, Chile, United States of America    0.000000
                                                        ...
Venezuela, Mexico                                     0.000000
Venezuela, United States of America                   0.000000
Venezuela, United States of America, Colombia         0.000000
Venezuela, United States of America, Spain            0.000000
Vietnam                                               0.400000
Name: genres, Length: 564, dtype: float64

In [102]:
country_comedy = country_grp['genres'].apply(no_of_true)
country_comedy

country
Algeria                                                1
Angola, Brazil                                         0
Argentina                                             15
Argentina, Brazil                                      1
Argentina, Brazil, Chile, United States of America     0
                                                      ..
Venezuela, Mexico                                      0
Venezuela, United States of America                    0
Venezuela, United States of America, Colombia          0
Venezuela, United States of America, Spain             0
Vietnam                                                4
Name: genres, Length: 564, dtype: int64

In [103]:
country_count = country_grp['show_id'].count()

In [104]:
country_count

country
Algeria                                                1
Angola, Brazil                                         1
Argentina                                             53
Argentina, Brazil                                      2
Argentina, Brazil, Chile, United States of America     1
                                                      ..
Venezuela, Mexico                                      1
Venezuela, United States of America                    2
Venezuela, United States of America, Colombia          1
Venezuela, United States of America, Spain             1
Vietnam                                               10
Name: show_id, Length: 564, dtype: int64

In [108]:
python_df = pd.concat([country_count, country_comedy], axis=1)

In [109]:
python_df

                                                    show_id  genres
country
Algeria                                                   1       1
Angola, Brazil                                            1       0
Argentina                                                53      15
Argentina, Brazil                                         2       1
Argentina, Brazil, Chile, United States of America        1       0
...                                                     ...     ...
Venezuela, Mexico                                         1       0
Venezuela, United States of America                       2       0
Venezuela, United States of America, Colombia             1       0
Venezuela, United States of America, Spain                1       0
Vietnam                                                  10       4

[564 rows x 2 columns]

In [114]:
python_df.rename(columns= {'show_id' : 'total_entries', 'genres' : 'total_comedy'}, inplace=True)

In [131]:
python_df['comedy_percent'] = python_df['total_comedy'] / python_df['total_entries'] * 100

In [132]:
python_df

,total_entries,total_comedy,comedy_percent
country,,,
Algeria,1,1,100.000000
"Angola, Brazil",1,0,0.000000
Argentina,53,15,28.301887
"Argentina, Brazil",2,1,50.000000
"Argentina, Brazil, Chile, United States of America",1,0,0.000000
...,...,...,...
"Venezuela, Mexico",1,0,0.000000
"Venezuela, United States of America",2,0,0.000000
"Venezuela, United States of America, Colombia",1,0,0.000000
"Venezuela, United States of America, Spain",1,0,0.000000
Vietnam,10,4,40.000000

In [134]:
python_df.sort_values(by= 'comedy_percent', ascending=False, inplace=True)

In [138]:
python_df.iloc[100:150]

,total_entries,total_comedy,comedy_percent
country,,,
"France, Brazil, United States of America",1,1,100.000000
"France, Germany, United States of America",1,1,100.000000
"France, Ireland, Italy, Taiwan, United States of America",1,1,100.000000
"United States of America, United Kingdom, Brazil, Germany, Mexico",1,1,100.000000
"Canada, United States of America, Italy",1,1,100.000000
"Argentina, United Kingdom",1,1,100.000000
"Argentina, Spain",3,3,100.000000
Slovenia,4,3,75.000000
"Denmark, United States of America",4,3,75.000000
New Zealand,13,9,69.230769
"United States of America, Spain",3,2,66.666667
"United States of America, Netherlands",3,2,66.666667
"Japan, China",8,5,62.500000
Lithuania,9,5,55.555556
"United States of America, Canada, United Kingdom",2,1,50.000000
"United States of America, Ireland",2,1,50.000000
"United States of America, Canada, Japan",2,1,50.000000
"United States of America, France",6,3,50.000000
"Argentina, Uruguay",2,1,50.000000
"New Zealand, United States of America",2,1,50.000000
Peru,10,5,50.000000
"South Korea, China",4,2,50.000000
"South Africa, United Kingdom, United States of America",2,1,50.000000
"South Korea, United States of America",24,12,50.000000
"United States of America, Australia",4,2,50.000000
"United Kingdom, Australia",2,1,50.000000
"Taiwan, United States of America",6,3,50.000000
"Hong Kong, China",4,2,50.000000
Luxembourg,2,1,50.000000
"Mexico, Spain, United States of America",2,1,50.000000
"Japan, South Korea, United States of America",4,2,50.000000
Latvia,2,1,50.000000
"Chile, United States of America",2,1,50.000000
"Argentina, Chile",2,1,50.000000
"Argentina, Brazil",2,1,50.000000
Iran,17,8,47.058824
"United States of America, Mexico",15,7,46.666667
Japan,1742,796,45.694604
Finland,29,13,44.827586
United Arab Emirates,7,3,42.857143
Russia,194,82,42.268041
Hungary,24,10,41.666667
Croatia,12,5,41.666667
Vietnam,10,4,40.000000
"Canada, Ireland, United States of America",5,2,40.000000
"France, United States of America",23,9,39.130435
Israel,54,21,38.888889
Norway,70,27,38.571429
Greece,52,20,38.461538
Serbia,21,8,38.095238