In [11]:
import pandas as pd

In [12]:
df = pd.read_csv('data1.csv')

In [14]:
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,genres,language,description,popularity,vote_count,vote_average
0,33238,TV Show,Running Man,안재철,"Yoo Jae-suk, Jee Seok-jin, Kim Jong-kook, Haha...",South Korea,2010-07-11,2010,8.241,1 Seasons,"Comedy, Reality",ko,A reality and competition show where members a...,1929.898,187,8.241
1,32415,TV Show,Conan,NaN,"Conan O'Brien, Andy Richter",United States of America,2010-11-08,2010,7.035,1 Seasons,"Talk, Comedy, News",en,A late night television talk show hosted by C...,1670.580,229,7.035
2,37757,TV Show,MasterChef Greece,NaN,NaN,Greece,2010-10-03,2010,5.600,1 Seasons,Reality,el,MasterChef Greece is a Greek competitive cooki...,1317.092,6,5.600
3,75685,TV Show,Prostřeno!,NaN,"Václav Vydra, Jana Boušková",Czech Republic,2010-03-01,2010,6.500,1 Seasons,Reality,cs,The knives (and forks) are out as a group of s...,1095.776,6,6.500
4,33847,TV Show,The Talk,NaN,"Amanda Kloots, Jerry O'Connell, Akbar Gbaja-Bi...","United States of America, Ireland",2010-10-18,2010,3.400,1 Seasons,Talk,en,A panel of well-known news and entertainment p...,712.070,12,3.400

In [15]:
df.columns

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'genres', 'language',
       'description', 'popularity', 'vote_count', 'vote_average'],
      dtype='str')

In [30]:
df.rename(columns = {'rating(of 10)' : 'points'}, inplace= True)

In [31]:
def reccomendation(rating):
    if rating < 6:
        return 'bad'
    else: 
        return 'good'

In [35]:
df['reccomendation'] = df['points'].apply(reccomendation)

In [36]:
df['reccomendation']

0        good
1        good
2         bad
3        good
4         bad
         ...
15995     bad
15996     bad
15997    good
15998     bad
15999     bad
Name: reccomendation, Length: 16000, dtype: str

In [45]:
df.shape

(16000, 17)

In [46]:
def time(year):
    if year < 2018:
        return 'old'
    else:
        return 'new'

In [49]:
df['gen'] = df['release_year'].apply(time)

In [50]:
df['gen']

0        old
1        old
2        old
3        old
4        old
        ...
15995    new
15996    new
15997    new
15998    new
15999    new
Name: gen, Length: 16000, dtype: str

In [60]:
df.sort_values(by= ['country', 'points'], ascending=[True, False], inplace=True)

In [62]:
df[['country', 'points']].head(50)

              country  points
1058          Algeria   5.800
6041   Angola, Brazil   7.700
9589        Argentina   8.793
15057       Argentina   8.700
7031        Argentina   8.600
7082        Argentina   8.400
14526       Argentina   8.300
6551        Argentina   8.200
12270       Argentina   8.053
7077        Argentina   8.000
6035        Argentina   7.900
1682        Argentina   7.900
14813       Argentina   7.700
5882        Argentina   7.600
12503       Argentina   7.500
7916        Argentina   7.300
1549        Argentina   7.300
2726        Argentina   7.300
1088        Argentina   7.300
3869        Argentina   7.000
2391        Argentina   6.900
7642        Argentina   6.000
11848       Argentina   5.900
2165        Argentina   5.700
8124        Argentina   5.500
12651       Argentina   5.500
6073        Argentina   5.200
1512        Argentina   5.000
8586        Argentina   5.000
7064        Argentina   4.600
338         Argentina   4.200
4130        Argentina   4.000
11268       Argentina   4.000
3535        Argentina   3.500
9039        Argentina   3.200
1726        Argentina   2.000
7354        Argentina   2.000
6576        Argentina   2.000
163         Argentina   2.000
2934        Argentina   2.000
7255        Argentina   2.000
9096        Argentina   2.000
10960       Argentina   2.000
4493        Argentina   2.000
10566       Argentina   2.000
977         Argentina   1.000
2430        Argentina   0.000
1952        Argentina   0.000
8216        Argentina   0.000
2630        Argentina   0.000

In [64]:
df['points'].nlargest(10)

13101    10.0
3754     10.0
4814     10.0
4898     10.0
6525     10.0
2039     10.0
11038    10.0
8306     10.0
10664    10.0
2431     10.0
Name: points, dtype: float64

In [65]:
df.nlargest(10, 'points')

,show_id,type,title,director,cast,country,date_added,release_year,points,duration,genres,language,description,popularity,vote_count,vote_average,reccomendation,gen
13101,225553,TV Show,Gran hermano,NaN,"Julio César Rodríguez, Diana Bolocco","Argentina, Chile",2023-06-18,2023,10.0,1 Seasons,Reality,es,NaN,82.164,1,10.0,good,new
3754,210690,TV Show,Shannons Club TV,NaN,"Mark Oastler, John Wright",Australia,2013-10-01,2013,10.0,1 Seasons,"Reality, Documentary",en,This series presents a number of unique vehicl...,24.192,1,10.0,good,old
4814,76021,TV Show,The Skinner Boys: Guardians of the Lost Secrets,NaN,"Damian Clarke, Lisa Moule, Paul Tylak, Derek S...",Australia,2014-08-02,2014,10.0,1 Seasons,"Action & Adventure, Animation, Drama, Family, ...",en,"World explorer Augustus Skinner has died. Now,...",23.658,1,10.0,good,old
4898,59631,TV Show,Get Ace,"Jack Christian, D.J. McPherson","Jeffery Richards, Lyall Brooks, Ian Bliss, Emi...","Australia, United States of America",2014-01-19,2014,10.0,1 Seasons,"Kids, Animation, Action & Adventure",en,"Meet Ace McDougal - just your average, everyda...",21.828,3,10.0,good,old
6525,91347,TV Show,Kuu Kuu Harajuku,NaN,"Maggie Chretien, Daisy Masterman, Emma Taylor-...","Australia, United States of America",2016-10-04,2016,10.0,1 Seasons,NaN,en,"Girl group HJ5, comprised of G with Love, Ange...",43.038,1,10.0,good,old
2039,48443,TV Show,Bergwelten,NaN,"Otto Clemens, Reinhold Messner",Austria,2012-01-26,2012,10.0,1 Seasons,Documentary,de,People experience adventures on mountains all ...,204.244,1,10.0,good,old
11038,241203,TV Show,Links. Rechts. Mitte – Duell der Meinungsmacher,NaN,"Katrin Prähauser, Christoph Kotanko, Michael F...",Austria,2021-02-14,2021,10.0,1 Seasons,Talk,de,NaN,117.053,1,10.0,good,new
8306,158036,TV Show,Bachelor Point,Kajal Arefin Ome,"Mishu Sabbir, Ziaul Hoque Polash, Chashi Alam,...",Bangladesh,2018-08-04,2018,10.0,1 Seasons,"Comedy, Drama, Family",bn,Four young men from different districts of Ban...,90.917,2,10.0,good,new
10664,114860,TV Show,The Masked Singer,NaN,Jens Dendoncker,Belgium,2020-09-18,2020,10.0,1 Seasons,"Family, Reality",nl,NaN,27.740,3,10.0,good,new
2431,84208,TV Show,Jabaloe,NaN,"Maarten Schuermans, Joyce Beullens, Danny Hout...",Belgium,2012-02-21,2012,10.0,1 Seasons,"Kids, Comedy",nl,NaN,33.521,1,10.0,good,old