In [135]:
people = {
    "first" : ["Chirag", "Sahil", "Yana"],
    "last" : ["Arora", "Arora", "Bindal"],
    "email" : ["chiragarora@email.com", "sahilarora@email.com", "yanabindal@email.com"]
}

In [136]:
import pandas as pd

In [137]:
df = pd.DataFrame(people)

In [138]:
df

    first    last                  email
0  Chirag   Arora  chiragarora@email.com
1   Sahil   Arora   sahilarora@email.com
2    Yana  Bindal   yanabindal@email.com

In [139]:
df.columns

Index(['first', 'last', 'email'], dtype='str')

In [140]:
df.columns = ['first_name', 'last_name', 'email_id']
df.columns

Index(['first_name', 'last_name', 'email_id'], dtype='str')

In [141]:
df

  first_name last_name               email_id
0     Chirag     Arora  chiragarora@email.com
1      Sahil     Arora   sahilarora@email.com
2       Yana    Bindal   yanabindal@email.com

In [142]:
df.columns = [str.upper(string) for string in df.columns]

In [143]:
df

  FIRST_NAME LAST_NAME               EMAIL_ID
0     Chirag     Arora  chiragarora@email.com
1      Sahil     Arora   sahilarora@email.com
2       Yana    Bindal   yanabindal@email.com

In [144]:
df.columns = df.columns.str.replace('_', ' ')

In [145]:
df.columns

Index(['FIRST NAME', 'LAST NAME', 'EMAIL ID'], dtype='str')

In [146]:
df

  FIRST NAME LAST NAME               EMAIL ID
0     Chirag     Arora  chiragarora@email.com
1      Sahil     Arora   sahilarora@email.com
2       Yana    Bindal   yanabindal@email.com

In [147]:
df.columns = df.columns.str.replace(' ', '_')

In [148]:
df.columns = df.columns.str.lower()

In [149]:
df.columns

Index(['first_name', 'last_name', 'email_id'], dtype='str')

In [150]:
df.rename (columns = {'first_name' : 'first', 'last_name' : 'last'} ,  inplace = True)

In [151]:
df

    first    last               email_id
0  Chirag   Arora  chiragarora@email.com
1   Sahil   Arora   sahilarora@email.com
2    Yana  Bindal   yanabindal@email.com

In [152]:
df.loc[2]

first                       Yana
last                      Bindal
email_id    yanabindal@email.com
Name: 2, dtype: str

In [153]:
df.loc[2] = ['Tana', 'Tindal', 'tanatindal@email.com']
df

    first    last               email_id
0  Chirag   Arora  chiragarora@email.com
1   Sahil   Arora   sahilarora@email.com
2    Tana  Tindal   tanatindal@email.com

In [154]:
df.loc[2, 'last'] = 'Bindal'
df

    first    last               email_id
0  Chirag   Arora  chiragarora@email.com
1   Sahil   Arora   sahilarora@email.com
2    Tana  Bindal   tanatindal@email.com

In [155]:
df.at[2, 'last'] = 'Tindal'
df

    first    last               email_id
0  Chirag   Arora  chiragarora@email.com
1   Sahil   Arora   sahilarora@email.com
2    Tana  Tindal   tanatindal@email.com

In [156]:
df.loc[0:1, 'email_id'] = df.loc[0:1, 'email_id'].str.upper()

In [157]:
df

    first    last               email_id
0  Chirag   Arora  CHIRAGARORA@EMAIL.COM
1   Sahil   Arora   SAHILARORA@EMAIL.COM
2    Tana  Tindal   tanatindal@email.com

In [158]:
df['email_id'] = df['email_id'].apply(str.upper)

In [159]:
df

    first    last               email_id
0  Chirag   Arora  CHIRAGARORA@EMAIL.COM
1   Sahil   Arora   SAHILARORA@EMAIL.COM
2    Tana  Tindal   TANATINDAL@EMAIL.COM

In [160]:
def lower_case(email):
    return email.lower()

In [161]:
df['email_id'] = df['email_id'].apply(lower_case)

In [162]:
df

    first    last               email_id
0  Chirag   Arora  chiragarora@email.com
1   Sahil   Arora   sahilarora@email.com
2    Tana  Tindal   tanatindal@email.com

In [163]:
df['email_id'] = df['email_id'].apply(lambda x: x.upper())

In [164]:
df

    first    last               email_id
0  Chirag   Arora  CHIRAGARORA@EMAIL.COM
1   Sahil   Arora   SAHILARORA@EMAIL.COM
2    Tana  Tindal   TANATINDAL@EMAIL.COM

In [165]:
df['email_id'] = df['email_id'].apply(lambda x: x.lower())

In [166]:
df.map(str.lower)

    first    last               email_id
0  chirag   arora  chiragarora@email.com
1   sahil   arora   sahilarora@email.com
2    tana  tindal   tanatindal@email.com

In [167]:
df.map(len)

   first  last  email_id
0      6     5        21
1      5     5        20
2      4     6        20

In [175]:
df['first'] = ['Chirag', 'Sahil', 'Yana']

In [176]:
df

    first    last               email_id
0  Chirag   Arora  chiragarora@email.com
1   Sahil   Arora   sahilarora@email.com
2    Yana  Tindal   tanatindal@email.com

In [178]:
df['first'].map({'Chirag' : 'Tilag', 'Sahil' : 'Tahil'})

0    Tilag
1    Tahil
2      NaN
Name: first, dtype: str

In [179]:
df

    first    last               email_id
0  Chirag   Arora  chiragarora@email.com
1   Sahil   Arora   sahilarora@email.com
2    Yana  Tindal   tanatindal@email.com

In [180]:
df['first'].replace({'Chirag' : 'Tilag', 'Sahil' : 'Tahil'})

0    Tilag
1    Tahil
2     Yana
Name: first, dtype: str

In [181]:
df

    first    last               email_id
0  Chirag   Arora  chiragarora@email.com
1   Sahil   Arora   sahilarora@email.com
2    Yana  Tindal   tanatindal@email.com

In [182]:
df['first'] = df['first'].replace({'Chirag' : 'Tilag', 'Sahil' : 'Tahil'})

In [183]:
df

   first    last               email_id
0  Tilag   Arora  chiragarora@email.com
1  Tahil   Arora   sahilarora@email.com
2   Yana  Tindal   tanatindal@email.com

In [186]:
df

   first    last               email_id    full_name
0  Tilag   Arora  chiragarora@email.com  Tilag Arora
1  Tahil   Arora   sahilarora@email.com  Tahil Arora
2   Yana  Tindal   tanatindal@email.com  Yana Tindal

In [188]:
df['first'] = df['first'].replace({'Tilag' : 'Chirag', 'Tahil': 'Sahil'})

In [189]:
df['last'] = df['last'].replace({'Tindal' : 'Bindal'})

In [190]:
df

    first    last               email_id    full_name
0  Chirag   Arora  chiragarora@email.com  Tilag Arora
1   Sahil   Arora   sahilarora@email.com  Tahil Arora
2    Yana  Bindal   tanatindal@email.com  Yana Tindal

In [191]:
# adding columns

In [192]:
df['full_name'] = df['first'] + ' ' + df['last']

In [193]:
df

    first    last               email_id     full_name
0  Chirag   Arora  chiragarora@email.com  Chirag Arora
1   Sahil   Arora   sahilarora@email.com   Sahil Arora
2    Yana  Bindal   tanatindal@email.com   Yana Bindal

In [194]:
# removing columns

In [196]:
df.drop(columns = ['first', 'last'], inplace=True)

In [197]:
df

                email_id     full_name
0  chiragarora@email.com  Chirag Arora
1   sahilarora@email.com   Sahil Arora
2   tanatindal@email.com   Yana Bindal

In [210]:
tf = df['full_name'].str.split(' ', expand=True)

In [211]:
tf

        0       1
0  Chirag   Arora
1   Sahil   Arora
2    Yana  Bindal

In [212]:
df[['first', 'last']] = tf

In [213]:
df

                email_id     full_name   first   lasst    last
0  chiragarora@email.com  Chirag Arora  Chirag   Arora   Arora
1   sahilarora@email.com   Sahil Arora   Sahil   Arora   Arora
2   tanatindal@email.com   Yana Bindal    Yana  Bindal  Bindal

In [215]:
df.drop(columns='lasst', inplace=True)

In [216]:
df

                email_id     full_name   first    last
0  chiragarora@email.com  Chirag Arora  Chirag   Arora
1   sahilarora@email.com   Sahil Arora   Sahil   Arora
2   tanatindal@email.com   Yana Bindal    Yana  Bindal