In [1]:
people = {
    "first" : ["Chirag", "Sahil", "Yana"],
    "last" : ["Arora", "Arora", "Bindal"],
    "email" : ["chiragarora@email.com", "sahilarora@email.com", "yanabindal@email.com"]
}

In [2]:
import pandas as pd

In [12]:
df = pd.DataFrame(people)

In [13]:
df

    first    last                  email
0  Chirag   Arora  chiragarora@email.com
1   Sahil   Arora   sahilarora@email.com
2    Yana  Bindal   yanabindal@email.com

In [20]:
df.sort_values(by='last', ascending=False, inplace=True)

In [21]:
df

    first    last                  email
2    Yana  Bindal   yanabindal@email.com
0  Chirag   Arora  chiragarora@email.com
1   Sahil   Arora   sahilarora@email.com

In [22]:
df.sort_values(by=['last', 'first'], ascending=False, inplace=True)

In [23]:
df

    first    last                  email
2    Yana  Bindal   yanabindal@email.com
1   Sahil   Arora   sahilarora@email.com
0  Chirag   Arora  chiragarora@email.com

In [24]:
df.sort_index()

    first    last                  email
0  Chirag   Arora  chiragarora@email.com
1   Sahil   Arora   sahilarora@email.com
2    Yana  Bindal   yanabindal@email.com

In [26]:
df['last'].sort_values()

1     Arora
0     Arora
2    Bindal
Name: last, dtype: str